workflows:
  android-workflow:
    name: Build Mahmoud ERP APK
    instance_type: mac_mini_m1
    scripts:
      - name: Install Flet Tool
        script: pip install flet
      - name: Run Mahmoud Build Script
        script: flet build apk --product "mahmoud" --release
    artifacts:
      - build/apk/*.apk
    publishing:
      email:
        recipients:
          - mahmuodnassni@gmail.com
